name: Deploy to WordPress.org

on:
  push:
    tags:
      - "v*"   # Only run when a new tag like v1.0.0 is pushed

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD }}
          SLUG: cranseo   
